serverName: Boys at the Back [Sleeping], waiting for his prince...
serverPort: 25565
maxPlayers: 20
loginMessage: ...Waking server up, come back in a minute...
serverOnlineMode: false
startMinecraft: true
minecraftCommand: java -Xms6G -Xmx8G -jar fabric-server.jar nogui
restartDelay: 5000
version: 1.20.1
useWhitelistFile: false
useBlacklistFiles: false
useNativeFiles: false
hideIpInLogs: true
hideOnConnectionLogs: true
